-- Basic
require("core/plugins")
require("core/mappings")
require("core/colors")
require("core/configs")

-- Plugins
require("plugins.hop")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.ruscmd")
require("plugins.masson")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.whichkey")
require("plugins.toggleterm")
